name: Build Whisper GGML Models

on:
  workflow_dispatch: # handmatig starten
  schedule:
    - cron: "0 3 * * 0" # wekelijks, elke zondag 03:00 UTC

jobs:
  build-whisper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget python3 python3-pip build-essential
          pip3 install numpy tqdm torch --index-url https://download.pytorch.org/whl/cpu

      - name: Download HuggingFace models
        run: |
          mkdir -p models-src
          for model in base small medium large-v3; do
            echo "Downloading $model..."
            mkdir -p models-src/$model
            git clone --depth 1 https://huggingface.co/openai/whisper-$model models-src/$model
          done

      - name: Convert models to GGML
        run: |
          for model in base small medium large-v3; do
            echo "Converting $model..."
            python3 models/convert-pt-to-ggml.py \
              models-src/$model \
              --outfile models/ggml-$model.bin
          done


      - name: Upload GGML models
        uses: actions/upload-artifact@v4
        with:
          name: whisper-ggml-models
          path: models/ggml-*.bin
