name: Build Whisper GGML Models

on:
  workflow_dispatch: # handmatig starten
  schedule:
    - cron: "0 3 * * 0" # wekelijks, elke zondag 03:00 UTC

jobs:
  build-whisper:
    runs-on: ubuntu-latest
    outputs:
      versions:
        description: Whisper GGML Models
        value: "base small medium large-v3"

    steps:
      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp

      - name: Install dependencies
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          sudo apt-get update
          sudo apt-get install -y git wget python3 python3-pip build-essential
          pip3 install numpy tqdm torch --index-url https://download.pytorch.org/whl/cpu
          mkdir -p ${{ github.workspace }}/models-src

      - name: Download HuggingFace models
        run: |
          git clone https://huggingface.co/openai/whisper-base ${{ github.workspace }}/models-src/base

      - name: Download HuggingFace models
        run: |
          git clone https://huggingface.co/openai/whisper-small ${{ github.workspace }}/models-src/small

      - name: Download HuggingFace models
        run: |
          git clone https://huggingface.co/openai/whisper-medium ${{ github.workspace }}/models-src/medium

      - name: Download HuggingFace models
        run: |
          git clone https://huggingface.co/openai/whisper-large-v3 ${{ github.workspace }}/models-src/large-v3

      - name: Convert models to GGML
        run: |
          mkdir -p ${{ github.workspace }}/output/models
          for model in ${{ steps.build-whisper.outputs.versions }}; do
            echo "Converting $model..."
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/$model \
              --outfile ${{ github.workspace }}/output/models/ggml-$model.bin
          done


      - name: Upload GGML models
        uses: actions/upload-artifact@v4
        with:
          name: whisper-ggml-models
          path: output/models/ggml-*.bin
