name: Download & Convert Whisper GGML Models

on:
  workflow_dispatch: # handmatig starten
  schedule:
    - cron: "0 3 * * 0" # wekelijks, elke zondag om 03:00 UTC

jobs:
  whisper-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          path: whisper.cpp

      - name: Download latest OpenAI models
        working-directory: whisper.cpp
        run: |
          ./models/download-ggml-model.sh base
          ./models/download-ggml-model.sh small
          ./models/download-ggml-model.sh medium
          ./models/download-ggml-model.sh large-v3

      - name: Convert models to .bin
        working-directory: whisper.cpp
        run: |
          files=("./models/ggml-base.bin" "./models/ggml-small.bin" "./models/ggml-medium.bin" "./models/ggml-large-v3.bin")
          for file in "${files[@]}"; do
            echo "Converting $file"
            python3 ./models/convert-pt-to-ggml.py "$file"
          done

      - name: Upload converted models
        uses: actions/upload-artifact@v4
        with:
          name: whisper-ggml-bin
          path: whisper.cpp/models/*.bin
