name: Build Whisper GGML Models

on:
  workflow_dispatch: # handmatig starten
  schedule:
    - cron: "0 3 * * 0" # wekelijks, elke zondag 03:00 UTC

jobs:
  build-whisper:
    runs-on: ubuntu-latest

    steps:
      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: false
      #     android: true
      #     dotnet: true
      #     haskell: true
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true

      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp
          ref: v1.7.6

      - name: Install dependencies
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          sudo apt-get update && sudo apt-get install -y git-lfs wget python3 python3-pip build-essential
          pip3 install numpy tqdm torch --index-url https://download.pytorch.org/whl/cpu
          mkdir -p ${{ github.workspace }}/models-src ${{ github.workspace }}/output/models

      - name: Download HuggingFace model base
        run: git clone https://huggingface.co/openai/whisper-base ${{ github.workspace }}/models-src/base

      - name: Download HuggingFace model small
        run: git clone https://huggingface.co/openai/whisper-small ${{ github.workspace }}/models-src/small

      - name: Download HuggingFace model medium
        run: git clone https://huggingface.co/openai/whisper-medium ${{ github.workspace }}/models-src/medium

      - name: Download HuggingFace model large-v3
        run: git clone https://huggingface.co/openai/whisper-large-v3 ${{ github.workspace }}/models-src/large-v3

      - name: Convert models to GGML base
        run: |
            echo "Converting base..."
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/base \
              --outfile ${{ github.workspace }}/output/models/ggml-base.bin

      - name: Convert models to GGML small
        run: |
            echo "Converting small..."
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/small \
              --outfile ${{ github.workspace }}/output/models/ggml-small.bin

      - name: Convert models to GGML medium
        run: |
            echo "Converting medium..."
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/medium \
              --outfile ${{ github.workspace }}/output/models/ggml-medium.bin

      - name: Convert models to GGML large-v3
        run: |
            echo "Converting large-v3..."
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/large-v3 \
              --outfile ${{ github.workspace }}/output/models/ggml-large-v3.bin

      - name: Upload GGML models
        uses: actions/upload-artifact@v4
        with:
          name: whisper-ggml-models
          path: output/models/ggml-*.bin
