name: Build Whisper GGML Models

on:
  push:
    branches:
      - master
  workflow_dispatch: # manual trigger from Actions tab
  schedule:
    - cron: "0 3 * * 0" # weekly, every sunday 03:00 UTC

jobs:
  build-base:
    uses: ./.github/workflows/build-model.yml
    with:
      model_name: "base"
      model_repo: "openai/whisper-base"

  build-small:
    uses: ./.github/workflows/build-model.yml
    with:
      model_name: "small"
      model_repo: "openai/whisper-small"

  build-medium:
    uses: ./.github/workflows/build-model.yml
    with:
      model_name: "medium"
      model_repo: "openai/whisper-medium"

  build-large-v3:
    uses: ./.github/workflows/build-model.yml
    with:
      model_name: "large-v3"
      model_repo: "openai/whisper-large-v3"

  combine-artifacts:
    needs: [build-base, build-small, build-medium, build-large-v3]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: whisper-ggml-model-*
          merge-multiple: true
          path: combined-models/

      - name: Upload combined artifacts
        uses: actions/upload-artifact@v4
        with:
          name: whisper-ggml-models
          path: combined-models/
