name: Build Whisper GGML Models

on:
  workflow_dispatch: # handmatig starten
  schedule:
    - cron: "0 3 * * 0" # wekelijks, elke zondag 03:00 UTC

jobs:
  build-whisper:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp
          ref: v1.7.6

      - name: Install dependencies
        run: |
          git config --global --add safe.directory ${{ github.workspace }}
          sudo apt-get update && sudo apt-get install -y git-lfs wget python3 python3-pip
          git lfs install
          pip3 install numpy tqdm torch --index-url https://download.pytorch.org/whl/cpu
          mkdir -p ${{ github.workspace }}/models-src ${{ github.workspace }}/output/models

  build-base-model:
    needs: build-whisper
    steps:
      - name: Download HuggingFace model base
        run: |
          echo "Available disk space before download:"
          df -h
          for i in {1..3}; do
            if git clone --depth 1 https://huggingface.co/openai/whisper-base ${{ github.workspace }}/models-src/base; then
              break
            else
              echo "Attempt $i failed, retrying..."
              rm -rf ${{ github.workspace }}/models-src/base
              sleep 5
            fi
          done

      - name: Convert models to GGML base
        run: |
            echo "Converting base..."
            echo "Disk space before conversion:"
            df -h
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/base \
              --outfile ${{ github.workspace }}/output/models/ggml-base.bin
            echo "Cleaning up base source files..."
            rm -rf ${{ github.workspace }}/models-src/base

  build-small-model:
    needs: build-whisper
    steps:
      - name: Download HuggingFace model small
        run: |
          echo "Available disk space before download:"
          df -h
          for i in {1..3}; do
            if git clone --depth 1 https://huggingface.co/openai/whisper-small ${{ github.workspace }}/models-src/small; then
              break
            else
              echo "Attempt $i failed, retrying..."
              rm -rf ${{ github.workspace }}/models-src/small
              sleep 5
            fi
          done

      - name: Convert models to GGML small
        run: |
            echo "Converting small..."
            echo "Disk space before conversion:"
            df -h
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/small \
              --outfile ${{ github.workspace }}/output/models/ggml-small.bin
            echo "Cleaning up small source files..."
            rm -rf ${{ github.workspace }}/models-src/small

  build-medium-large-model:
    needs: build-whisper
    steps:
      - name: Download HuggingFace model medium
        run: |
          echo "Available disk space before download:"
          df -h
          for i in {1..3}; do
            if git clone --depth 1 https://huggingface.co/openai/whisper-medium ${{ github.workspace }}/models-src/medium; then
              break
            else
              echo "Attempt $i failed, retrying..."
              rm -rf ${{ github.workspace }}/models-src/medium
              sleep 10
            fi
          done

      - name: Convert models to GGML medium
        run: |
            echo "Converting medium..."
            echo "Disk space before conversion:"
            df -h
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/medium \
              --outfile ${{ github.workspace }}/output/models/ggml-medium.bin
            echo "Cleaning up medium source files..."
            rm -rf ${{ github.workspace }}/models-src/medium

  build-large-model:
    needs: build-whisper
    steps:
      - name: Download HuggingFace model large-v3
        run: |
          echo "Available disk space before download:"
          df -h
          for i in {1..3}; do
            if git clone --depth 1 https://huggingface.co/openai/whisper-large-v3 ${{ github.workspace }}/models-src/large-v3; then
              break
            else
              echo "Attempt $i failed, retrying..."
              rm -rf ${{ github.workspace }}/models-src/large-v3
              sleep 10
            fi
          done

      - name: Convert models to GGML large-v3
        run: |
            echo "Converting large-v3..."
            echo "Disk space before conversion:"
            df -h
            python3 ${{ github.workspace }}/models/convert-pt-to-ggml.py \
              ${{ github.workspace }}/models-src/large-v3 \
              --outfile ${{ github.workspace }}/output/models/ggml-large-v3.bin
            echo "Cleaning up large-v3 source files..."
            rm -rf ${{ github.workspace }}/models-src/large-v3

  upload-models:
    needs: [build-base-model, build-small-model, build-medium-large-model, build-large-model]
    steps:
      - name: Upload GGML models
        uses: actions/upload-artifact@v4
        with:
          name: whisper-ggml-models
          path: output/models/ggml-*.bin
