name: Build Whisper GGML Models

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      whispercpp-version: ${{ steps.get-whispercpp-version.outputs.version }}
    steps:
      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggml-org/whisper.cpp
          ref: v1.7.6

      - name: Extract whisper.cpp version
        id: get-whispercpp-version
        run: |
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION)
          elif [ -d .git ]; then
            VERSION=$(git describe --tags --abbrev=0)
          else
            VERSION="unknown"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create version tag
        id: create-tag
        run: |
          VERSION=$(date +'%Y.%m.%d')
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${VERSION}.$(date +'%H%M')"
          fi
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Create draft release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create-tag.outputs.tag }}
          name: "Whisper GGML Models ${{ steps.create-tag.outputs.tag }}"
          body: |
            # Whisper GGML Models Release ${{ steps.create-tag.outputs.tag }}
            
            This release contains GGML-converted Whisper models for use with whisper.cpp and compatible applications.
            
            ## Models Included
            - **ggml-base.bin** - Base model (~150MB)
            - **ggml-small.bin** - Small model (~500MB) 
            - **ggml-medium.bin** - Medium model (~1.5GB)
            - **ggml-large-v3.bin** - Large v3 model (~3GB, split into parts due to GitHub size limits)
            
            ## Usage
            These models can be used directly with:
            - [whisper.cpp](https://github.com/ggml-org/whisper.cpp)
            - [whisper-desktop](https://github.com/Const-me/Whisper)
            - Any application supporting GGML Whisper models
            
            ## How to Reassemble the Large Model
            After downloading all parts (e.g., `ggml-large-v3.bin.part-aa`, `ggml-large-v3.bin.part-ab`, ...), run the following command in the folder with the parts:
            
            **Linux / macOS (Terminal):**
            ```sh
            cat ggml-large-v3.bin.part-* > ggml-large-v3.bin
            ```
            
            **Windows (Command Prompt):**
            ```cmd
            copy /b ggml-large-v3.bin.part-aa+ggml-large-v3.bin.part-ab+ggml-large-v3.bin.part-ac ggml-large-v3.bin
            ```
            *(Add all part filenames in order, separated by `+`.)*
            
            **Windows (PowerShell):**
            ```powershell
            Get-Content .\ggml-large-v3.bin.part-* -Raw | Set-Content .\ggml-large-v3.bin -AsByteStream
            ```
            
            ## Build Information
            - Built from: whisper.cpp ${{ steps.get-whispercpp-version.outputs.version }}
            - Source models: OpenAI Whisper (HuggingFace)
            - Build date: ${{ steps.create-tag.outputs.tag }}
            
            Generated automatically by GitHub Actions.
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-base:
    needs: create-release
    uses: ./.github/workflows/build-model.yml
    with:
      model_name: "base"
      model_repo: "openai/whisper-base"
      release_upload_url: ${{ needs.create-release.outputs.upload_url }}

  build-small:
    needs: create-release
    uses: ./.github/workflows/build-model.yml
    with:
      model_name: "small"
      model_repo: "openai/whisper-small"
      release_upload_url: ${{ needs.create-release.outputs.upload_url }}

  build-medium:
    needs: create-release
    uses: ./.github/workflows/build-model.yml
    with:
      model_name: "medium"
      model_repo: "openai/whisper-medium"
      release_upload_url: ${{ needs.create-release.outputs.upload_url }}

  build-large-v3:
    needs: create-release
    uses: ./.github/workflows/build-model.yml
    with:
      model_name: "large-v3"
      model_repo: "openai/whisper-large-v3"
      release_upload_url: ${{ needs.create-release.outputs.upload_url }}

  publish-release:
    needs: [create-release, build-base, build-small, build-medium, build-large-v3]
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.tag }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}